const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Anchor,
		C3.Behaviors.Fade,
		C3.Behaviors.scrollto,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.PlayByName
	];
};
self.C3_JsPropNameTable = [
	{Variables: 0},
	{startW: 0},
	{Tween: 0},
	{bar_progress: 0},
	{bg_bar: 0},
	{nodeid: 0},
	{startX: 0},
	{startY: 0},
	{DragDrop: 0},
	{dice: 0},
	{nIdex: 0},
	{free: 0},
	{dice2: 0},
	{dice3: 0},
	{Anchor: 0},
	{fade: 0},
	{Fade: 0},
	{flash: 0},
	{gameover: 0},
	{ScrollTo: 0},
	{game_manager: 0},
	{line: 0},
	{player_emiter: 0},
	{Rotate: 0},
	{player_particles: 0},
	{roll: 0},
	{Sine: 0},
	{tutorial: 0},
	{btnClose: 0},
	{btnSound: 0},
	{btnSpawn: 0},
	{Audio: 0},
	{Browser: 0},
	{btnContinuar: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{Touch: 0},
	{txtFrase: 0},
	{name: 0},
	{txtUI: 0},
	{txtUI2: 0},
	{goGame: 0},
	{taptoplay: 0},
	{transition: 0},
	{Dices: 0},
	{Buttons: 0},
	{layerIn: 0},
	{layerOut: 0},
	{FADESPEED: 0},
	{Layout: 0},
	{newLayer: 0},
	{posX: 0},
	{posY: 0},
	{cant: 0},
	{SCORE: 0},
	{LASTDICE: 0},
	{TUTORIAL: 0},
	{defeat: 0},
	{cantsix: 0},
	{spawndice: 0},
	{mag: 0},
	{dur: 0},
	{timegame: 0},
	{GAMENAME_SAVE: 0},
	{TOTLEVELS: 0}
];

self.InstanceType = {
	Variables: class extends self.IArrayInstance {},
	bar_progress: class extends self.ITiledBackgroundInstance {},
	bg_bar: class extends self.ISpriteInstance {},
	dice: class extends self.ISpriteInstance {},
	dice2: class extends self.ISpriteInstance {},
	dice3: class extends self.ISpriteInstance {},
	fade: class extends self.ISpriteInstance {},
	flash: class extends self.ISpriteInstance {},
	game_manager: class extends self.ISpriteInstance {},
	line: class extends self.ISpriteInstance {},
	player_emiter: class extends self.IParticlesInstance {},
	player_particles: class extends self.ISpriteInstance {},
	roll: class extends self.ISpriteInstance {},
	tutorial: class extends self.ISpriteInstance {},
	btnClose: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	btnSpawn: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	btnContinuar: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	txtFrase: class extends self.ISpriteFontInstance {},
	txtUI: class extends self.ISpriteFontInstance {},
	txtUI2: class extends self.ISpriteFontInstance {},
	taptoplay: class extends self.ISpriteInstance {},
	transition: class extends self.ISpriteInstance {},
	Dices: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {}
}